brew install --cask \
    android-file-transfer \
    bazecor \
    brave-browser \
    coconutbattery \
    daisydisk \
    docker \
    dropbox \
    evernote \
    fanny \
    fantastical \
    flux \
    hiddenbar \
    iterm2 \
    karabiner-elements \
    kindle \
    macdown \
    microsoft-teams \
    notion \
    postman \
    protonvpn \
    rectangle \
    roam-research \
    slack \
    spotify \
    sublime-text \
    tableplus \
    telegram \
    the-unarchiver \
    transmission \
    visual-studio-code \
    vlc \
    whatsapp \
    xmind \
    zoom
